### ISSUE TITLE
Change user avatar

### ISSUE THREAD

**Issue by KikeBL** [lveteau/lightdm-webkit-modern-arch-theme#1]
Can not change user avatar

I put a .face named image on home directory but has not effect

**Comment by lveteau** [comment]
Hi 👋 

Normally, it's lightdm who takes care of handling your session avatar, you simply have to change it from your desktop manager settings panel. 

As explained here, try to set it explicitly in lightdm config file : https://wiki.archlinux.org/title/LightDM#Changing_your_avatar

If it still doesn't work, you can try to override it by creating an img folder at the root folder of this projet, and put your user svg avatar in this folder under the name "avatar.svg". 
If you want to set a png/jpg, change the script.js file right here https://github.com/lveteau/lightdm-webkit-modern-arch-theme/blob/master/script.js#L248 and set the correct file extension

If it still doesn't work, replace this whole block in script.js line 244 :

```js
    if (user.image) {
      image.src = user.image;
      image.onerror = on_image_error;
    } else {
      image.src = "img/avatar.svg";
    }
```
with 
```js
image.src = "img/avatar.svg"
```
Sorry this project isn't very extensible out of the box, it was mostly made for private use and I decided to release it when I stopped used lightdm-webkit 😅 

Let me know if this fixed your problem, if not, i'll be happy to take a closer look and maybe release a fix !

**Comment by KikeBL** [comment]
All perfect, thnx
